### PR TITLE
adding example for standalone UCM for monitoring Eaton UPS over SNMP

### PR DESCRIPTION
**Pull request by nkrasko**

### CODE REVIEW

**Review by rnovatorov — COMMENTED** [review]
Hi @nkrasko, thank you for your contribution.

I have added a few changes to correctly execute sync code in async context and to make the code overall more Pythonic.

Could you please confirm that your integration still works and does what you intended it to do?

**Comment by nkrasko** [comment]
@rnovatorov, unfortunatelly this one is failing:

`nvk@ikigai snmp-eaton-ups % docker-compose up
[+] Running 1/0
 ✔ Container snmp-eaton-ups-snmp-eaton-ups-ucm-1  Created                                                                                                            0.0s
Attaching to snmp-eaton-ups-snmp-eaton-ups-ucm-1
snmp-eaton-ups-snmp-eaton-ups-ucm-1  | {"time": "2023-07-21T16:12:38.715443", "level": "INFO", "name": "enapter.mqtt.client", "host": "mqtt.enapter.com", "port": 8883, "message": "starting"}
snmp-eaton-ups-snmp-eaton-ups-ucm-1  | {"time": "2023-07-21T16:12:38.737050", "level": "ERRO", "name": "enapter.vucm.logger", "hardware_id": "S819964A3C61F4829158728D69A5B003E", "channel_id": "default", "message": "device task 'get_telemetry_data' failed: AttributeError(\"module 'enapter.async_' has no attribute 'run_in_executor'\")"}
snmp-eaton-ups-snmp-eaton-ups-ucm-1  | {"time": "2023-07-21T16:12:39.567015", "level": "INFO", "name": "enapter.mqtt.client", "host": "mqtt.enapter.com", "port": 8883, "message": "client ready"}
snmp-eaton-ups-snmp-eaton-ups-ucm-1  | {"time": "2023-07-21T16:12:39.571586", "level": "ERRO", "name": "enapter.vucm.logger", "hardware_id": "S819964A3C61F4829158728D69A5B003E", "channel_id": "default", "message": "device task 'get_properties_data' failed: AttributeError(\"module 'enapter.async_' has no attribute 'run_in_executor'\")"}
snmp-eaton-ups-snmp-eaton-ups-ucm-1  | {"time": "2023-07-21T16:12:39.798536", "level": "ERRO", "name": "enapter.mqtt.client", "host": "mqtt.enapter.com", "port": 8883, "exc_info": "Traceback (most recent call last):\n  File \"/app/.venv/lib/python3.10/site-packages/aiomqtt/client.py\", line 786, in _on_subscribe\n    fut = self._pending_subscribes.pop(mid)\nKeyError: 3", "message": "Unexpected message ID \"3\" in on_subscribe callback"}
snmp-eaton-ups-snmp-eaton-ups-ucm-1  | {"time": "2023-07-21T16:12:39.804346", "level": "INFO", "name": "enapter.mqtt.client", "host": "mqtt.enapter.com", "port": 8883, "message": "client not ready"}
snmp-eaton-ups-snmp-eaton-ups-ucm-1  | Traceback (most recent call last):
snmp-eaton-ups-snmp-eaton-ups-ucm-1  |   File "/app/script.py", line 127, in <module>
snmp-eaton-ups-snmp-eaton-ups-ucm-1  |     asyncio.run(main())
snmp-eaton-ups-snmp-eaton-ups-ucm-1  |   File "/usr/local/lib/python3.10/asyncio/runners.py", line 44, in run
snmp-eaton-ups-snmp-eaton-ups-ucm-1  |     return loop.run_until_complete(main)
snmp-eaton-ups-snmp-eaton-ups-ucm-1  |   File "/usr/local/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
snmp-eaton-ups-snmp-eaton-ups-ucm-1  |     return future.result()
snmp-eaton-ups-snmp-eaton-ups-ucm-1  |   File "/app/script.py", line 17, in main
snmp-eaton-ups-snmp-eaton-ups-ucm-1  |     await enapter.vucm.run(device_factory)
snmp-eaton-ups-snmp-eaton-ups-ucm-1  |   File "/app/.venv/lib/python3.10/site-packages/enapter/vucm/app.py", line 13, in run
snmp-eaton-ups-snmp-eaton-ups-ucm-1  |     async with App(config=config, device_factory=device_factory) as app:
snmp-eaton-ups-snmp-eaton-ups-ucm-1  |   File "/app/.venv/lib/python3.10/site-packages/enapter/async_/routine.py", line 16, in __aexit__
snmp-eaton-ups-snmp-eaton-ups-ucm-1  |     await self.stop()
snmp-eaton-ups-snmp-eaton-ups-ucm-1  |   File "/app/.venv/lib/python3.10/site-packages/enapter/async_/routine.py", line 48, in stop
snmp-eaton-ups-snmp-eaton-ups-ucm-1  |     await self.join()
snmp-eaton-ups-snmp-eaton-ups-ucm-1  |   File "/app/.venv/lib/python3.10/site-packages/enapter/async_/routine.py", line 55, in join
snmp-eaton-ups-snmp-eaton-ups-ucm-1  |     self._task.result()
snmp-eaton-ups-snmp-eaton-ups-ucm-1  | AttributeError: module 'enapter.async_' has no attribute 'run_in_executor'
snmp-eaton-ups-snmp-eaton-ups-ucm-1 exited with code 1
nvk@ikigai snmp-eaton-ups %`

**Comment by rnovatorov** [comment]
@nkrasko, thank you for trying the changes out and attaching the error log.

From the traceback I see that I have forgotten to update the version of the SDK to `0.7.3`. This should be now fixed.

Could you try again please?

**Comment by nkrasko** [comment]
Same issue - doesn't help

**Comment by rnovatorov** [comment]
@nkrasko, I have found a race condition, that I had accidentally added while refactoring the code. The issue was that both telemetry sender and properties sender tried to simultaneously call thread-unsafe `getCmd` method.

Could you be so kind to try again?

**Pull request merged**
